server:
  port: 8090

spring:
  devtools:
    restart:
      enabled: true
      #添加那个目录的文件需要restart
      additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: static/**
  thymeleaf:
    content-type: text/html
    mode: LEGACYHTML5
    cache: false
  datasource:
    name: myworld
#    url: jdbc:mysql://127.0.0.1:3306/xxx?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
#    username: xxx
#    password: xxx
    url: jdbc:mysql://106.75.134.13:33062/myworld?useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    username: myworld
    password: myworld!@#
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # 指定静态资源路径
  mvc:
    static-path-pattern: /admin/*
    view:
      prefix: /admin
      suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yunsheng.huiyuanhui.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: classpath:logback-spring.xml
